#+TITLE: Blog Content


* Technology
** Linux

*** How to use dual function keys
*** How to use

** Web development

*** Build a personal portfolio site.
*** Build a live together dating site.
***

** Programming


*** Solve programming problems for the leetcode
*** Dynamic programming with dynamic problems.

** Projects

*** Make tic tac toe game with AI.
*** Make a chess engine and a game with AI.
*** Build a chat bot.

* Books
* Nature & Life


What was it I was doing? How many words have I written so far. Not very much is it? Sometimes I feel like this isn't what it looks like. And I would very much like to do so to not get attached to the things that feels like raw and slumber and all those party tricks with all those much people and to get their heartfelia and to this day we have all this production and all these empty feelings inside myself are just like those angry homeculus and to think we can all do this while sitting here is amazing and to think we have justified all those years.

What is life and What do we know about it?
We know nothing about nothing to feel this empty feeling inside myself. Just let it out. Write about it and don't think about it. To all those people who think I am a failure. I'm telling you all that if you don't know what these people think about all day. It's really painful and to think that I'm here to tell you all about this. I feel like I've won a lottery and to this I have achieved what outsider people call calamity and to think about those other things that are so sophisticated and to think we have been lucky to do this so unintentionaly and to think
