
* Sit down and think.

 All of humanity's problem stem from man's inability to sit quietly in a room alone.
 Modern humans virtually spend no time on "inward-directed thought"
 We mistake ourselves for individual, isolated beings, trapped within our heads.
 People detest being made to spend 10 to 15 minutes in a room alone to do nothing but thinking. even to the extent of being willing to give themsleves a mild electric shock.


* how to think like a programmer - talk

** new var
    * Name : what to call this thing?
    * Type : what type of data will this variable hold?
    * InitVal : what is the starting value of this variable?

      type name = InitVal

** while algo
    * sentry : var that will control loop
    * Initilization Vaue : code that initializes sentry
    * condition : loop repeats if condition is true
    * change code : code to change sentry so condition can be triggered.
** Reversed built-in function in python
    reverses the built-in function in python. returns an iterative object that can be used by the loop to use this.

** <2021-01-05 Tue>

* What is madlibs? - It's a wordplay game.


* What to do when life kicks you down to a gravel spot?
* Do you want to die alone?
* Do some research on lonliness.
* What is social anxiety?

What is this sensation. what is this feeling growing inside me. It feels like it's going to Burst Open.


* What was it that I was thinking of? I don't remember such things. Fuck it. I don't even knwo where to start.

I need to learn about pandas and data science.
Where to start?


* How to be normal like other people and not an introvert

I don't know. That the answer I can think of. Do what other peoples do. Be happy But I'm always happy. But I am also lonely and alone. But sometimes it feels good but sometimes it doesn't. Do anybody know why this happen? Fuck I don't know nothing.

** Shuvro's rules for being normal.

+ Read newspaper and Be up to date with your country and the world.
+ Use facebook twitter and instagram.
+ Use Messenger and what's up too.
+ Be good with your friends and other co-worker
+ Be an idiot. Talk with those people and agree that they are right.
+ Don't give anybody philospical advice. Coz they won't get it.
+ Give time to your families
+ Be a good family and friends type of people.
+ Compliment other people for nothing.
+ Make other people happy.
+ Don't think about universe and other spiritual things. They don't matter to these people.

Where's the time do all this fucking shit? I mean life too fucking short. Which path should I choose and why?
What is the universe. Should I make myself happy or other people.

Will somebody give me all these answers? Fuck if I know it.
Fuck Fuck Fuck all people and fuck this planet. Somebody get me out of this shithole of country. Fuck what am I even doing?

* Let's scour the internet and find something interesting to work on.
* My take on programming and art.

Programming and art. How are they related. I think in a big it's like creating something out of nothing. Like you're creating something other people can't. People can come up with original ideas and concepts. It's just a matter of preference. Everyone's taste is different. There's no denying that. Even I know about all of this things. I am the pincale of everybody's alter ego. Programming is creating something. It could be something new or something old being rewritten. But the original idea is always there. Like I have an algorithm. And that is an idea. You just have to embrace it. Why don't have something that isn't legal or illegal. Fuck if I know it. You can bring the same idea to reality in many different ways. There's no obvious or one single solution to any problem. There's always more than one solution. All you have to do is find it.


* What is turbulance. ?
* Research about barnum effect.
* Learn origami
* Are we free to make decisions. Everything is binary every decision ever made.
* Hysterical Strength
* Programming or girlfriend?
* Copy reading or writing in hdd.
* Ason pete gf er loge khawadaw
* Buy 2 and get 60% back afterwards build a website for that.
* Rashi with fairy tail link
* Love a girl but don't get horny with her but others - Research
* Opposite dating app like programmer vs programmer
* Dating or devs site then for all and most compatible and complete opposite personality.
* A moment in life sotry about dreaming then dying
* Ai data science app about how much tv have I watched and similiar series movie recommnadation.
* Set new principles for my life.
* Learn music. Learn about programming music.

* Where were we at the end of the previous thought??
* What is Brain Dump
* everything in this universe is about balance. If you find the right balance you can do anything, any miracle. you just have to belive it. Everything can be expalained by physics.


* Coursera Data Science Pro Cert
** Data Science

Data Scientist find solutions to problems by analyzing data and makes stories out of that data to communicate with others. Data Scientists have a curious mind, knowledge about analytics and the ability to communicate about their findings.

Data Science is something that Data Scientists do. Data Science is a concept of unifying statistics, scientific methods, algorithms, data analysis, machine learning and their related field to understand and analyze data.


* Hudai... What can I do?
