#+TITLE: Org Mode
#+AUTHOR: Shuvrojit Biswas

* Introduction

Org mode is emacs mode based on outline mode. has some unique feature sets that we need to deal with right now. Meta means Alt.

Shortcut for source code blocks: <sTAB

** Interactive Font Sizes

command ~text-scale-adjust~ has three keybindings:
=text-scale-increate=
=text-scale-decrease=

    * =C-x C-+= (increase font size)
    * =C-x C--= (decrease font size)
    * =C-x C-0= (reset to default font size)

Bind these functions with =C-+= =C--=.

#+begin_src emacs-lisp
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
#+end_src

** Highlight current line

uilt in global minor mode ~global-hl-line-mode~. You can change the highlighted color by adjusting the value of ~hl-line-face~ face.

#+begin_src emacs-lisp
(global-hl-line-mode +1)
(hl-line-face <value>)
#+end_src

** Moving Lines

Here's function for moving lines up and down. First two separate functions was created. One for moving line up and another for moving line down. Then we define the keybindings for that.

#+begin_src emacs-lisp
(defun move-line-up ()
  "Move up the current line."
  (interactive)
  (transpose-lines 1)
  (forward-line -2)
  (indent-according-to-mode))

(defun move-line-down ()
  "Move down the current line."
  (interactive)
  (forward-line 1)
  (transpose-lines 1)
  (forward-line -1)
  (indent-according-to-mode))

;; set the keybindings for these functions
(define-key evil-normal-state-map (kbd "C-k") 'move-line-up)
(define-key evil-normal-state-map (kbd "C-j") 'move-line-down)
#+end_src

** Tables

Tables are very easy and smart to create. Type "|" at the beginning of a line and create a cell or block then press TAB it will automatically create the table for you.

| This will be cell //press tab
| This is next |
|           |

** Workspaces

You have workspaces inside emacs too. You can create as many workspaces you can. In doom emacs you can move between workspaces by pressing meta+1/2/3... You can create new workspaces by pressing SPC+TAB+n.

** Pretty

#+begin_src emacs-lisp
;; Changing Org mode headline bullet lists
(setq org-superstar-headline-bullets-list '("⁖" "◉" "○" "✸" "✿"))
(setq org-bullets-bullet-list '("⁖"))

;; Hide emphasis markers like ... after headlines
(setq org-hide-emphasis-markers t)

;; setting custom font size for headlines
(custom-set-faces
 '(org-level-1 ((t (:inherit outline-1 :height 1.8))))
 '(org-level-2 ((t (:inherit outline-2 :height 1.6))))
 '(org-level-3 ((t (:inherit outline-3 :height 1.4))))
 '(org-level-4 ((t (:inherit outline-4 :height 1.3))))
 '(org-level-5 ((t (:inherit outline-5 :height 1.2))))
 )
#+end_src

You can make org documents look beautiful by using pretty. The default headline stars can be changed by setting up variables.

*** Changing the Font size for Headlines

By using custom-set-faces we can set font size to the different level of org outlines. we can set the height and width too.

so to

** Entertainment

*** Spotify

** Quitting
src_<elisp>{<(setq confirm-kill-emacs nill)>}

*** Automatic kill process on quit

#+begin_src emacs-lisp
(setq confirm-kill-processes nil)
#+end_src
